apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bmstest
  name: bmstest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmstest
  template:
    metadata:
      labels:
        app: bmstest
    spec:
      containers:
      - image: public.ecr.aws/c4g9r2g6/bms:latest
        name: bms
        ports:
        - containerPort: 4567

