apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srmtest
  name: srmtest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srmtest
  template:
    metadata:
      labels:
        app: srmtest
    spec:
      containers:
      - image: andyweldon/srm:1.3
        name: srm